service: worker-sqs

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  receiver:
    handler: index.receiver
    timeout: 30

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'yarn'
    packagerOptions:
      scripts:
        - prisma generate
