name: Ence SQS Pipeline

on:
  push:
    branches:
      - use-sqs
jobs:
  Deploy-SQS:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install and Link Local Dependencies
        working-directory: packages/
        run: |
          cd db && npm install && npm link && cd ../
          cd helpers && npm install && npm link && cd ../
          cd generate-media && npm install && npm link && cd ../

      - name: Add Linked Dependencies to package.json of services/event-process
        working-directory: services/event-process/
        run: |
          for pkg in db helpers generate-media; do
            cd ../packages/$pkg && npm install && npm link && cd ../../services/event-process/
          done
          npm install
          cat package.json

      - name: Making Runtime File for AWS Lambda
        working-directory: services/event-process/
        run: |
          npm install -g typescript  
          tsc index.ts --target esnext --module NodeNext --moduleResolution NodeNext

      - name: Deploy using Serverless
        working-directory: services/event-process/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLS_INTERACTIVE_SETUP_ENABLE: 1
        run: |
          npx serverless deploy
